services:
  user-service:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - user-db

  user-db:
    image: postgres:latest
    env_file:
      - .env.production
    ports:
      - "5432:5432"
